import { Sheet, JobApplication } from "@/types";

export const INITIAL_SHEETS: Sheet[] = [
  {
    id: "sheet-applications",
    name: "Active Applications",
    description: "Track all your active job applications, phone screens, and interviews",
    icon: "Briefcase",
    color: "blue",
    createdAt: new Date(Date.now() - 35 * 86400000).toISOString(),
  },
  {
    id: "sheet-interviews",
    name: "Interviews & Offers",
    description: "Shortlisted roles with active interview loops, final rounds, and offers",
    icon: "Award",
    color: "emerald",
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: "sheet-wishlist",
    name: "Dream Companies",
    description: "Target companies and roles saved for future applications and networking",
    icon: "Sparkles",
    color: "purple",
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
];

export const INITIAL_JOBS: JobApplication[] = [
  {
    id: "job-1",
    sheetId: "sheet-applications",
    company: "Google",
    companyUrl: "https://google.com",
    role: "Senior Software Engineer (Cloud AI)",
    status: "Applied",
    companyType: "Big Tech",
    workplaceType: "Hybrid",
    location: "Mountain View, CA",
    salaryMin: 180000,
    salaryMax: 260000,
    salaryCurrency: "USD",
    appliedDate: "2026-07-20",
    jobUrl: "https://careers.google.com",
    contact: "Sarah Jenkins (Recruiter)",
    notes: "Applied via referral from Cloud AI team. Waiting for recruiter screen confirmation.",
    rating: 5,
    priority: "High",
    createdAt: new Date(Date.now() - 32 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: "job-2",
    sheetId: "sheet-applications",
    company: "Stripe",
    companyUrl: "https://stripe.com",
    role: "Staff Frontend Infrastructure Engineer",
    status: "Technical",
    companyType: "Scaleup",
    workplaceType: "Remote",
    location: "San Francisco, CA (Remote)",
    salaryMin: 195000,
    salaryMax: 245000,
    salaryCurrency: "USD",
    appliedDate: "2026-07-22",
    jobUrl: "https://stripe.com/jobs",
    contact: "Alex Chen (Engineering Manager)",
    notes: "Passed recruiter screen. 90-min live coding session scheduled for Friday.",
    rating: 5,
    priority: "High",
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "job-3",
    sheetId: "sheet-interviews",
    company: "Vercel",
    companyUrl: "https://vercel.com",
    role: "Senior Full-Stack Engineer (Next.js Core)",
    status: "Offer",
    companyType: "Scaleup",
    workplaceType: "Remote",
    location: "New York, NY (Remote)",
    salaryMin: 210000,
    salaryMax: 250000,
    salaryCurrency: "USD",
    appliedDate: "2026-07-25",
    jobUrl: "https://vercel.com/careers",
    contact: "Guillermo Rauch / Talent Team",
    notes: "Received formal offer letter! Base $225k + equity options. Reviewing compensation package.",
    rating: 5,
    priority: "High",
    createdAt: new Date(Date.now() - 27 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "job-4",
    sheetId: "sheet-interviews",
    company: "Linear",
    companyUrl: "https://linear.app",
    role: "Product Engineer (Desktop & Systems)",
    status: "Behavioral",
    companyType: "Startup",
    workplaceType: "Remote",
    location: "San Francisco, CA (Remote)",
    salaryMin: 175000,
    salaryMax: 215000,
    salaryCurrency: "USD",
    appliedDate: "2026-07-28",
    jobUrl: "https://linear.app/careers",
    contact: "Elena Rostova (Head of Product)",
    notes: "Final founder interview & culture fit round completed. Decision expected early next week.",
    rating: 5,
    priority: "High",
    createdAt: new Date(Date.now() - 24 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "job-5",
    sheetId: "sheet-applications",
    company: "Datadog",
    companyUrl: "https://datadoghq.com",
    role: "Senior Distributed Systems Engineer",
    status: "Screening",
    companyType: "Mid-size",
    workplaceType: "Hybrid",
    location: "Boston, MA",
    salaryMin: 165000,
    salaryMax: 205000,
    salaryCurrency: "USD",
    appliedDate: "2026-07-30",
    jobUrl: "https://datadoghq.com/careers",
    contact: "Michael Vance (Senior Recruiter)",
    notes: "Completed 30-minute initial phone call. System design assessment scheduled.",
    rating: 4,
    priority: "Medium",
    createdAt: new Date(Date.now() - 22 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: "job-6",
    sheetId: "sheet-wishlist",
    company: "Anthropic",
    companyUrl: "https://anthropic.com",
    role: "AI Systems & Infrastructure Engineer",
    status: "Wishlist",
    companyType: "Startup",
    workplaceType: "On-site",
    location: "San Francisco, CA",
    salaryMin: 220000,
    salaryMax: 300000,
    salaryCurrency: "USD",
    appliedDate: "2026-08-01",
    jobUrl: "https://anthropic.com/careers",
    contact: "LinkedIn Network Outreach",
    notes: "Target role for AI Safety infra. Requesting warm intro via alumni network.",
    rating: 5,
    priority: "High",
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: "job-7",
    sheetId: "sheet-applications",
    company: "Airbnb",
    companyUrl: "https://airbnb.com",
    role: "Senior Backend Engineer (Search & Discovery)",
    status: "Rejected",
    companyType: "Big Tech",
    workplaceType: "Remote",
    location: "San Francisco, CA",
    salaryMin: 185000,
    salaryMax: 235000,
    salaryCurrency: "USD",
    appliedDate: "2026-08-03",
    jobUrl: "https://careers.airbnb.com",
    contact: "Automated Rejection Email",
    notes: "Position put on hold internally. Recruiter advised to re-apply next quarter.",
    rating: 4,
    priority: "Low",
    createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: "job-8",
    sheetId: "sheet-applications",
    company: "Figma",
    companyUrl: "https://figma.com",
    role: "Software Engineer (Canvas Rendering)",
    status: "Applied",
    companyType: "Scaleup",
    workplaceType: "Hybrid",
    location: "San Francisco, CA",
    salaryMin: 175000,
    salaryMax: 220000,
    salaryCurrency: "USD",
    appliedDate: "2026-08-05",
    jobUrl: "https://figma.com/careers",
    contact: "Recruiter via Careers Portal",
    notes: "Submitted application with portfolio attachment highlighting WebGL projects.",
    rating: 4,
    priority: "Medium",
    createdAt: new Date(Date.now() - 16 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: "job-9",
    sheetId: "sheet-interviews",
    company: "Supabase",
    companyUrl: "https://supabase.com",
    role: "Developer Advocate & Platform Engineer",
    status: "Offer",
    companyType: "Startup",
    workplaceType: "Remote",
    location: "Remote (Global)",
    salaryMin: 160000,
    salaryMax: 195000,
    salaryCurrency: "USD",
    appliedDate: "2026-08-08",
    jobUrl: "https://supabase.com/careers",
    contact: "Paul Copplestone (CEO)",
    notes: "Offer received following open-source contribution review. Base $180k + token allocation.",
    rating: 5,
    priority: "High",
    createdAt: new Date(Date.now() - 13 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "job-10",
    sheetId: "sheet-applications",
    company: "Meta",
    companyUrl: "https://meta.com",
    role: "Production Engineer (Infrastructure & Systems)",
    status: "Screening",
    companyType: "Big Tech",
    workplaceType: "Hybrid",
    location: "Menlo Park, CA",
    salaryMin: 190000,
    salaryMax: 250000,
    salaryCurrency: "USD",
    appliedDate: "2026-08-10",
    jobUrl: "https://metacareers.com",
    contact: "David Miller (Technical Recruiter)",
    notes: "Recruiter screen passed. Preparing for C++/Linux kernel coding round.",
    rating: 5,
    priority: "High",
    createdAt: new Date(Date.now() - 11 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "job-11",
    sheetId: "sheet-interviews",
    company: "OpenAI",
    companyUrl: "https://openai.com",
    role: "Research Engineer (Model Evaluation & Alignment)",
    status: "Technical",
    companyType: "Startup",
    workplaceType: "On-site",
    location: "San Francisco, CA",
    salaryMin: 250000,
    salaryMax: 350000,
    salaryCurrency: "USD",
    appliedDate: "2026-08-12",
    jobUrl: "https://openai.com/careers",
    contact: "Jessica Zhao (Talent Partner)",
    notes: "Take-home machine learning architecture assignment submitted. Interview scheduled.",
    rating: 5,
    priority: "High",
    createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "job-12",
    sheetId: "sheet-wishlist",
    company: "Apple",
    companyUrl: "https://apple.com",
    role: "iOS System Frameworks Engineer",
    status: "Wishlist",
    companyType: "Big Tech",
    workplaceType: "On-site",
    location: "Cupertino, CA",
    salaryMin: 170000,
    salaryMax: 230000,
    salaryCurrency: "USD",
    appliedDate: "2026-08-14",
    jobUrl: "https://jobs.apple.com",
    contact: "SVP Org Referral",
    notes: "Networking via WWDC alumni group. Tailoring resume for CoreOS team.",
    rating: 4,
    priority: "Medium",
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: "job-13",
    sheetId: "sheet-applications",
    company: "Cloudflare",
    companyUrl: "https://cloudflare.com",
    role: "Edge Computing Systems Engineer",
    status: "Applied",
    companyType: "Scaleup",
    workplaceType: "Remote",
    location: "Austin, TX (Remote)",
    salaryMin: 160000,
    salaryMax: 210000,
    salaryCurrency: "USD",
    appliedDate: "2026-08-15",
    jobUrl: "https://cloudflare.com/careers",
    contact: "Recruiter via Greenhouse",
    notes: "Applied directly on career site for Workers team.",
    rating: 4,
    priority: "Medium",
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: "job-14",
    sheetId: "sheet-interviews",
    company: "Notion",
    companyUrl: "https://notion.so",
    role: "Full Stack Engineer (Realtime Sync & Editor)",
    status: "Behavioral",
    companyType: "Scaleup",
    workplaceType: "Hybrid",
    location: "San Francisco, CA",
    salaryMin: 180000,
    salaryMax: 225000,
    salaryCurrency: "USD",
    appliedDate: "2026-08-17",
    jobUrl: "https://notion.so/careers",
    contact: "Chris Park (Engineering Director)",
    notes: "Completed engineering culture & team collaboration interview. Waiting for final offer decision.",
    rating: 5,
    priority: "High",
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "job-15",
    sheetId: "sheet-applications",
    company: "Snowflake",
    companyUrl: "https://snowflake.com",
    role: "Senior Database Kernel Developer",
    status: "Withdrawn",
    companyType: "Mid-size",
    workplaceType: "Hybrid",
    location: "San Mateo, CA",
    salaryMin: 175000,
    salaryMax: 230000,
    salaryCurrency: "USD",
    appliedDate: "2026-08-18",
    jobUrl: "https://snowflake.com/careers",
    contact: "Karen Smith (Recruiter)",
    notes: "Withdrew application after receiving competing offer from Vercel.",
    rating: 3,
    priority: "Low",
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "job-16",
    sheetId: "sheet-applications",
    company: "Palantir",
    companyUrl: "https://palantir.com",
    role: "Forward Deployed Software Engineer",
    status: "Applied",
    companyType: "Mid-size",
    workplaceType: "On-site",
    location: "Denver, CO",
    salaryMin: 165000,
    salaryMax: 215000,
    salaryCurrency: "USD",
    appliedDate: "2026-08-20",
    jobUrl: "https://palantir.com/careers",
    contact: "Recruiter via Campus Alumni Network",
    notes: "Submitted application for Gotham platform engineering team.",
    rating: 4,
    priority: "Medium",
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];
